### ISSUE TITLE
Can't seem to make it work

### ISSUE THREAD

**Issue by SchRita** [Youka/SSBRenderer#3]
I'm really interested but can't seem to make it work. :S
I'm using Windows 8.1 x64 and Aegisub 3.2.0 32bit/64bit > I tried to place the respective dll files into the csri folder, in the 64bit version of Aegisub it doesn't show up in the list; in the 32bit version it shows up, but when used no text appears on screen.
I'm using the latest version of SSBRenderer, 0.0.4, downloaded from SourceForge.

If you need any more information, let me know. I'm sorry for troubling you, I'm really interested in testing this renderer and all my problems may be my fault for not reading something (then feel free to get angry at me ^^).

**Comment by Youka** [comment]
Your text may be not shown because of your missing understanding of the differences between ASS and SSB. ASS defines zero alpha as fully opaque and is the default value for Aegisub, but SSB is the opposite (zero alpha = fully transparent). Additionally SSB defines scale in decimal range (1.0 = 100%), ASS as percentage (100 = 100%).

Why SSBRenderer doesn't get found by Aegisub 64 i can just guess. As note: Aegisub 64 can't load/use the 32 bits version of the renderer.

Look [this demo](https://www.youtube.com/watch?v=eknQ5g5eGeE) for a visual guide. For questions relating to the format itself, [this forum](http://forum.youka.de/index.php/Board/16-SSB/) is the right place.

**Comment by darealshinji** [comment]
My Aegisub 3.2.0 on Ubuntu can't find it either. I have tried to install it in $HOME/.aegisub/csri, /usr/share/aegisub/csri and /usr/local/lib, but it could only find libass as available subtitle renderer.

**Comment by Youka** [comment]
Some quotes from @nielsmh aka **jfs**:

> csri can work on unix as well
> it was used back when asa was a thing
> although the unix code paths haven't been used for years, but they shouldn't particularly have rotted
> also I'm not sure if the configure script is able to set up csri, actually
> if you enable the csri renderer interface in aegisub but don't link the csri wrapper library, but instead link your renderer directly to aegisub, then it should also work

So it may be an issue of Aegisub configuration.

**Comment by SchRita** [comment]
Thank you for your fast reply, actually, your videos led me here but I failed to realise how important it was to set the alpha. >.<
I'll look into how I can configure Aegisub so that I can use the 64bit version as well. It's just strange that the 64bit version of VSFilterMod is shown, while the SSBRenderer is not.
Thanks again and good luck with the development.
